version: '3.7'
services:
  app:
    image: spring-boot-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8443"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      KEYSTORE_ALIAS: ${KEYSTORE_ALIAS}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
